version: "3.1"


services:

  app:
    build:
      context: .
    restart: always
    volumes:
      - ./:/ontrack/app
    depends_on:
      - database
    ports:
      - "80:3000"
      - "3035:3035"
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      SECRET_KEY_BASE: super-secret
      DATABASE_URL: postgres://ontrack:secret@database/ontrack

  database:
    image: bitnami/postgresql:latest
    volumes:
      - database:/bitnami/postgresql
    environment:
      POSTGRESQL_PASSWORD: secret
      POSTGRESQL_USERNAME: ontrack
      POSTGRESQL_DATABASE: ontrack


volumes:
  database: {}
